url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Phillip Suwan Kirwin" # the name of your site, e.g. ACME Corp.
description: "MASc Electrical and Computer Engineering Student at the University of British Columbia - Quantum Matter Institute"
