menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
social:
- {icon: 'github', link: 'https://github.com/pSKirwin'}
- {icon: 'instagram', link: 'https://instagram.com/phillip.kirwin'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/phillip-kirwin/'}